services:

  api-server:
    build: .
    image: spring-evaluasihum:1.0.0
    container_name: backendapp_container
    ports:
      - '8082:8082'
    env_file:
      - .env
    networks:
      - psr-app
    depends_on:
      - database
    restart: always #optional dont use it if your apps still got many bugs

  react-app:
    image: reactjs-evaluasihum:1.0.0
    container_name: reactapp_container
    ports:
      - '5173:5173'
    networks:
      - psr-app
    depends_on:
      - api-server
    restart: always #optional dont use it if your apps still got many bugs

  database:
    container_name: postgres_container
    ports:
      - '5432:5432'
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-data:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - psr-app
    restart: always

networks:
  psr-app:
    driver: bridge

volumes:
  postgres-data:
    driver: local