version: "3.9"
services:
  react-app:
    image: reactjs/evaluasihum:1.0.0
    container_name: reactapp_container
    ports:
      - '5173:5173'
    networks:
      - psr-app
    depends_on:
      - api-server
  api-server:
    build: .
    image: spring-evaluasihum:1.0.0
    container_name: backendapp_container
    ports:
      - '8082:8082'
    environment:
      database-url: jdbc:postgresql://database:5432/evaluasihum
      database-username: postgres
      database-password: admin
    networks:
      - psr-app
    depends_on:
      - database
  database:
    container_name: postgres_container
    ports:
      - '5432:5432'
    image: postgres:latest
    environment:
      - .env
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - psr-app
    restart: always
networks:
  psr-app:
   driver: bridge
volumes:
  postgres-data:
    driver: local